# Generated by Django 4.2.1 on 2023-07-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('ticket_number', models.CharField(max_length=10, unique=True)),
                ('facebook_interests', models.TextField(blank=True)),
                ('pinterest_interests', models.TextField(blank=True)),
            ],
        ),
    ]
