# Generated by Django 4.2.1 on 2023-07-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='facebook_interests',
            new_name='interests',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='pinterest_interests',
        ),
    ]
