# Generated by Django 4.2.1 on 2023-07-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_rename_facebook_interests_ticket_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='interests',
        ),
        migrations.AddField(
            model_name='ticket',
            name='interest',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter')], default=None, max_length=20),
        ),
    ]
