# Generated by Django 4.2.3 on 2023-07-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_remove_ticket_interest_ticket_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='social_media_platform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
